version: '3'

services:
  server:
    build:
      context: /server
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
  client:
    build:
      context: /
      dockerfile: Dockerfile
    ports:
      - "3000:3000"