version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "8082:8082"
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER_URL=http://server:8082